export const builtin_variable = ['true', 'false', 'unset', 'a_ahkpath', 'a_ahkversion', 'a_allowmainwindow', 'a_appdata', 'a_appdatacommon', 'a_args', 'a_clipboard', 'a_computername', 'a_comspec', 'a_controldelay', 'a_coordmodecaret', 'a_coordmodemenu', 'a_coordmodemouse', 'a_coordmodepixel', 'a_coordmodetooltip', 'a_cursor', 'a_dd', 'a_ddd', 'a_dddd', 'a_defaultmousespeed', 'a_desktop', 'a_desktopcommon', 'a_detecthiddentext', 'a_detecthiddenwindows', 'a_endchar', 'a_eventinfo', 'a_fileencoding', 'a_hotkeyinterval', 'a_hotkeymodifiertimeout', 'a_hour', 'a_iconfile', 'a_iconhidden', 'a_iconnumber', 'a_icontip', 'a_index', 'a_initialworkingdir', 'a_is64bitos', 'a_isadmin', 'a_iscompiled', 'a_iscritical', 'a_ispaused', 'a_issuspended', 'a_keydelay', 'a_keydelayplay', 'a_keyduration', 'a_keydurationplay', 'a_language', 'a_lasterror', 'a_linefile', 'a_linenumber', 'a_listlines', 'a_loopfield', 'a_loopfileattrib', 'a_loopfiledir', 'a_loopfileext', 'a_loopfilefullpath', 'a_loopfilename', 'a_loopfilepath', 'a_loopfileshortname', 'a_loopfileshortpath', 'a_loopfilesize', 'a_loopfilesizekb', 'a_loopfilesizemb', 'a_loopfiletimeaccessed', 'a_loopfiletimecreated', 'a_loopfiletimemodified', 'a_loopreadline', 'a_loopregkey', 'a_loopregname', 'a_loopregtimemodified', 'a_loopregtype', 'a_maxhotkeysperinterval', 'a_mday', 'a_menumaskkey', 'a_min', 'a_mm', 'a_mmm', 'a_mmmm', 'a_mon', 'a_mousedelay', 'a_mousedelayplay', 'a_msec', 'a_mydocuments', 'a_now', 'a_nowutc', 'a_osversion', 'a_priorhotkey', 'a_priorkey', 'a_programfiles', 'a_programs', 'a_programscommon', 'a_ptrsize', 'a_regview', 'a_screendpi', 'a_screenheight', 'a_screenwidth', 'a_scriptdir', 'a_scriptfullpath', 'a_scripthwnd', 'a_scriptname', 'a_sec', 'a_sendlevel', 'a_sendmode', 'a_space', 'a_startmenu', 'a_startmenucommon', 'a_startup', 'a_startupcommon', 'a_storecapslockmode', 'a_tab', 'a_temp', 'a_thisfunc', 'a_thishotkey', 'a_tickcount', 'a_timeidle', 'a_timeidlekeyboard', 'a_timeidlemouse', 'a_timeidlephysical', 'a_timesincepriorhotkey', 'a_timesincethishotkey', 'a_titlematchmode', 'a_titlematchmodespeed', 'a_traymenu', 'a_username', 'a_wday', 'a_windelay', 'a_windir', 'a_workingdir', 'a_yday', 'a_year', 'a_yweek', 'a_yyyy'];
export const builtin_variable_h = ['a_ahkdir', 'a_dlldir', 'a_dllpath', 'a_globalstruct', 'a_isdll', 'a_mainthreadid', 'a_memorymodule', 'a_modulehandle', 'a_scriptstruct', 'a_threadid'];
export const builtin_ahkv1_commands = ['autotrim', 'blockinput', 'click', 'clipwait', 'control', 'controlclick', 'controlfocus', 'controlget', 'controlgetfocus', 'controlgetpos', 'controlgettext', 'controlmove', 'controlsend', 'controlsendraw', 'controlsettext', 'coordmode', 'critical', 'detecthiddentext', 'detecthiddenwindows', 'drive', 'driveget', 'drivespacefree', 'envadd', 'envdiv', 'envget', 'envmult', 'envset', 'envsub', 'envupdate', 'exit', 'exitapp', 'fileappend', 'filecopy', 'filecopydir', 'filecreatedir', 'filecreateshortcut', 'filedelete', 'fileencoding', 'filegetattrib', 'filegetshortcut', 'filegetsize', 'filegettime', 'filegetversion', 'fileinstall', 'filemove', 'filemovedir', 'fileopen', 'fileread', 'filereadline', 'filerecycle', 'filerecycleempty', 'fileremovedir', 'fileselectfile', 'fileselectfolder', 'filesetattrib', 'filesettime', 'format', 'formattime', 'getkeystate', 'gosub', 'groupactivate', 'groupadd', 'groupclose', 'groupdeactivate', 'gui', 'guicontrol', 'guicontrolget', 'hotkey', 'ifequal', 'ifexist', 'ifgreater', 'ifgreaterorequal', 'ifless', 'iflessorequal', 'ifmsgbox', 'ifnotequal', 'ifnotexist', 'ifwinactive', 'ifwinexist', 'ifwinnotactive', 'ifwinnotexist', 'imagesearch', 'inidelete', 'iniread', 'iniwrite', 'input', 'inputbox', 'keywait', 'listlines', 'menu', 'mouseclick', 'mouseclickdrag', 'mousegetpos', 'mousemove', 'msgbox', 'onerror', 'onexit', 'outputdebug', 'pause', 'pixelgetcolor', 'pixelsearch', 'postmessage', 'process', 'progress', 'random', 'regdelete', 'regread', 'regwrite', 'run', 'runas', 'runwait', 'send', 'sendevent', 'sendinput', 'sendlevel', 'sendmessage', 'sendmode', 'sendplay', 'sendraw', 'setbatchlines', 'setcapslockstate', 'setcontroldelay', 'setdefaultmousespeed', 'setenv', 'setformat', 'setkeydelay', 'setmousedelay', 'setnumlockstate', 'setregview', 'setscrolllockstate', 'setstorecapslockmode', 'settimer', 'settitlematchmode', 'setwindelay', 'setworkingdir', 'shutdown', 'sleep', 'sort', 'soundbeep', 'soundget', 'soundgetwavevolume', 'soundplay', 'soundset', 'soundsetwavevolume', 'splashimage', 'splashtextoff', 'splashtexton', 'splitpath', 'statusbargettext', 'statusbarwait', 'stringcasesense', 'stringleft', 'stringlower', 'stringright', 'stringtrimleft', 'stringtrimright', 'stringupper', 'suspend', 'sysget', 'thread', 'tooltip', 'transform', 'traytip', 'urldownloadtofile', 'winactivate', 'winactivatebottom', 'winclose', 'winget', 'wingetactivestats', 'wingetactivetitle', 'wingetclass', 'wingetpos', 'wingettext', 'wingettitle', 'winhide', 'winkill', 'winmaximize', 'winmenuselectitem', 'winminimize', 'winminimizeall', 'winminimizeallundo', 'winmove', 'winrestore', 'winset', 'winsettitle', 'winshow', 'winwait', 'winwaitactive', 'winwaitclose', 'winwaitnotactive'];

export const a_vars: Record<string, string> = { space: ' ', tab: '\t' };
export const dllcalltpe = ['str', 'astr', 'wstr', 'int64', 'int', 'uint', 'short', 'ushort', 'char', 'uchar', 'float', 'double', 'ptr', 'uptr', 'hresult'];

export const chinese_punctuations: Record<string, string> = {
	'，': ',',
	'。': '.',
	'；': ';',
	'‘': "'",
	'’': "'",
	'【': '[',
	'】': ']',
	'《': '<',
	'》': '>',
	'？': '?',
	'：': ':',
	'“': '"',
	'”': '"',
	'（': '(',
	'）': ')',
	'！': '!'
};

export const jsDocTagNames = [
	"abstract",
	"access",
	"alias",
	"argument",
	"async",
	"augments",
	"author",
	"borrows",
	"callback",
	"class",
	"classdesc",
	"constant",
	"constructor",
	"constructs",
	"copyright",
	"default",
	"deprecated",
	"description",
	"emits",
	"enum",
	"event",
	"example",
	"exports",
	"extends",
	"external",
	"field",
	"file",
	"fileoverview",
	"fires",
	"function",
	"generator",
	"global",
	"hideconstructor",
	"host",
	"ignore",
	"implements",
	"inheritdoc",
	"inner",
	"instance",
	"interface",
	"kind",
	"lends",
	"license",
	"link",
	"linkcode",
	"linkplain",
	"listens",
	"member",
	"memberof",
	"method",
	"mixes",
	"module",
	"name",
	"namespace",
	"overload",
	"override",
	"package",
	"param",
	"private",
	"prop",
	"property",
	"protected",
	"public",
	"readonly",
	"requires",
	"returns",
	"satisfies",
	"see",
	"since",
	"static",
	"summary",
	"template",
	"this",
	"throws",
	"todo",
	"tutorial",
	"type",
	"typedef",
	"var",
	"variation",
	"version",
	"virtual",
	"yields"
];